### ISSUE TITLE
problem with command in readme

### ISSUE THREAD

**Issue by twinec** [coolreader18/homebrew-desktop#3]
when I execute the command in your readme, it does this
bash: sudo: command not found
what should I do?

**Comment by coolreader18** [comment]
Sorry, I know this is late, but what OS are you running? Windows with cygwin or something, or what Linux distro?

**Comment by twinec** [comment]
i am running windows 10 using git

**Comment by coolreader18** [comment]
I think you can just run the command without the sudo in front.

**Comment by twinec** [comment]
thanks for the help. EDIT: without the sudo. it gives me bash: docker: command not found

**Comment by coolreader18** [comment]
Install docker, then. https://docker.com

Alternatively, you could just follow the other build instructions in the README, the ones for developing, if docker doesn't work.
